# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "995a8b44ef695c921b178dcd7a690b6c"
application_url = "https://survival-islands-mineral-icon.trycloudflare.com"
embedded = true
name = "theme-app-extensions"
handle = "theme-app-extensions-18"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://survival-islands-mineral-icon.trycloudflare.com/auth/callback",
  "https://survival-islands-mineral-icon.trycloudflare.com/auth/shopify/callback",
  "https://survival-islands-mineral-icon.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "zeeper-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
